### ISSUE TITLE
Create more typography styles.

### ISSUE THREAD

**Issue by v4ku1a** [muraha/tom-s-hardware-mockup-#2]
we need to add more typography styles to 
https://github.com/muraha/tom-s-hardware-mockup-/blob/master/app/scss/Base/_base.scss

styles like headers,
small text
links (color: #263341; hover active: #D8383B; visited: #8C9EB1) - there are different colors for links, we can use this for now,
here are few examples:
https://github.com/twbs/bootstrap/blob/v4-dev/scss/_type.scss  - bootstrap typography
https://github.com/zurb/foundation-sites/blob/develop/scss/typography/_base.scss#L362  - links from foundation framework

also helper classes would not hurt:
// Alignment
.text-left           { text-align: left; }
.text-right          { text-align: right; }
.text-center         { text-align: center; }
.text-justify        { text-align: justify; }
.text-nowrap         { white-space: nowrap; }

// Transformation
.text-lowercase      { text-transform: lowercase; }
.text-uppercase      { text-transform: uppercase; }
.text-capitalize     { text-transform: capitalize; }

.c-text-ellipsis {
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

**Comment by muraha** [comment]
@v4ku1a please check and close
